package com.example.taskmanager.routes

import com.example.taskmanager.calendar.GoogleCalendarService
import com.example.taskmanager.db.EventService
import com.example.taskmanager.models.Event // Local Event model
import com.example.taskmanager.routes.dto.*
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.time.format.DateTimeParseException

fun Route.eventRoutes(
    eventService: EventService,
    googleCalendarService: GoogleCalendarService
) {

    val isoDateTimeFormatter = DateTimeFormatter.ISO_LOCAL_DATE_TIME

    fun String.toLocalDateTimeSafe(): LocalDateTime? {
        return try {
            LocalDateTime.parse(this, isoDateTimeFormatter)
        } catch (e: DateTimeParseException) {
            null
        }
    }

    fun Event.toResponseDTO(): EventResponse {
        return EventResponse(
            id = this.id,
            googleCalendarEventId = this.googleCalendarEventId,
            title = this.title,
            description = this.description,
            startTime = this.startTime.format(isoDateTimeFormatter),
            endTime = this.endTime.format(isoDateTimeFormatter),
            location = this.location,
            virtualMeetingLink = this.virtualMeetingLink,
            teamId = this.teamId,
            creatorId = this.creatorId
        )
    }

    route("/users/{userId}/events") {
        post {
            val principalUserId = call.parameters["userId"]?.toIntOrNull() // In real app, from auth context
            if (principalUserId == null) {
                call.respond(HttpStatusCode.BadRequest, "User ID must be an integer.")
                return@post
            }

            val request = call.receive<EventCreateRequest>()

            val startTime = request.startTime.toLocalDateTimeSafe()
            val endTime = request.endTime.toLocalDateTimeSafe()

            if (startTime == null || endTime == null) {
                call.respond(HttpStatusCode.BadRequest, "Invalid start or end time format. Use ISO_LOCAL_DATE_TIME.")
                return@post
            }
            if (endTime.isBefore(startTime)) {
                call.respond(HttpStatusCode.BadRequest, "End time cannot be before start time.")
                return@post
            }

            var localEvent = Event(
                id = 0, // Will be generated by DB
                googleCalendarEventId = null,
                title = request.title,
                description = request.description,
                startTime = startTime,
                endTime = endTime,
                location = request.location,
                virtualMeetingLink = request.virtualMeetingLink,
                teamId = request.teamId,
                creatorId = principalUserId
            )

            val createdLocalEvent = eventService.createEvent(
                title = localEvent.title,
                description = localEvent.description,
                startTime = localEvent.startTime,
                endTime = localEvent.endTime,
                location = localEvent.location,
                virtualMeetingLink = localEvent.virtualMeetingLink,
                teamId = localEvent.teamId,
                creatorId = localEvent.creatorId
            )

            if (createdLocalEvent == null) {
                call.respond(HttpStatusCode.InternalServerError, "Failed to create event locally.")
                return@post
            }
            localEvent = createdLocalEvent // Update with generated ID and any other DB defaults

            // Attempt to create in Google Calendar if user has authorized
            try {
                val googleEventId = googleCalendarService.createEvent(principalUserId, localEvent)
                if (googleEventId != null) {
                    val updatedWithGoogleId = eventService.updateEventGoogleId(localEvent.id, googleEventId)
                    if (updatedWithGoogleId) {
                        localEvent = localEvent.copy(googleCalendarEventId = googleEventId)
                    } else {
                        application.log.warn("Failed to update local event ${localEvent.id} with GoogleCalId $googleEventId")
                        // Non-fatal for client, event is created locally. Could schedule a retry.
                    }
                }
            } catch (e: IllegalStateException) { // Thrown by getAuthorizedCalendarClient if no token
                application.log.info("User $principalUserId has not authorized Google Calendar: ${e.message}")
                // Non-fatal: Event is created locally. Client can be informed.
            } catch (e: Exception) {
                application.log.error("Failed to create Google Calendar event for user $principalUserId, local event ${localEvent.id}: ${e.message}", e)
                // Non-fatal for client.
            }

            call.respond(HttpStatusCode.Created, localEvent.toResponseDTO())
        }

        get {
            val principalUserId = call.parameters["userId"]?.toIntOrNull()
             if (principalUserId == null) {
                call.respond(HttpStatusCode.BadRequest, "User ID must be an integer.")
                return@get
            }
            val events = eventService.getEventsByCreator(principalUserId)
            call.respond(events.map { it.toResponseDTO() })
        }

        get("/{eventId}") {
            val principalUserId = call.parameters["userId"]?.toIntOrNull()
            val eventId = call.parameters["eventId"]?.toIntOrNull()
            if (principalUserId == null || eventId == null) {
                call.respond(HttpStatusCode.BadRequest, "User ID and Event ID must be integers.")
                return@get
            }

            val event = eventService.getEventById(eventId)
            if (event == null || event.creatorId != principalUserId) { // Basic authorization
                call.respond(HttpStatusCode.NotFound, "Event not found or access denied.")
                return@get
            }
            call.respond(event.toResponseDTO())
        }

        put("/{eventId}") {
            val principalUserId = call.parameters["userId"]?.toIntOrNull()
            val eventId = call.parameters["eventId"]?.toIntOrNull()
             if (principalUserId == null || eventId == null) {
                call.respond(HttpStatusCode.BadRequest, "User ID and Event ID must be integers.")
                return@put
            }

            val request = call.receive<EventUpdateRequest>()
            var existingLocalEvent = eventService.getEventById(eventId)
            if (existingLocalEvent == null || existingLocalEvent.creatorId != principalUserId) {
                call.respond(HttpStatusCode.NotFound, "Event not found or access denied.")
                return@put
            }

            val newStartTime = request.startTime?.toLocalDateTimeSafe()
            val newEndTime = request.endTime?.toLocalDateTimeSafe()

            if ((request.startTime != null && newStartTime == null) || (request.endTime != null && newEndTime == null)) {
                call.respond(HttpStatusCode.BadRequest, "Invalid start or end time format. Use ISO_LOCAL_DATE_TIME.")
                return@put
            }

            val currentStartTime = newStartTime ?: existingLocalEvent.startTime
            val currentEndTime = newEndTime ?: existingLocalEvent.endTime
            if (currentEndTime.isBefore(currentStartTime)) {
                 call.respond(HttpStatusCode.BadRequest, "End time cannot be before start time.")
                return@put
            }

            val localUpdateSuccess = eventService.updateEvent(
                id = eventId,
                title = request.title,
                description = request.description,
                startTime = newStartTime,
                endTime = newEndTime,
                location = request.location,
                virtualMeetingLink = request.virtualMeetingLink,
                teamId = request.teamId,
                googleCalendarEventId = null, // Not updated through this DTO directly
                clearDescription = request.clearDescription ?: false,
                clearLocation = request.clearLocation ?: false,
                clearVirtualMeetingLink = request.clearVirtualMeetingLink ?: false,
                clearTeamId = request.clearTeamId ?: false
            )

            if (!localUpdateSuccess) {
                call.respond(HttpStatusCode.InternalServerError, "Failed to update event locally.")
                return@put
            }

            var updatedLocalEvent = eventService.getEventById(eventId)!! // Re-fetch to get merged state

            if (updatedLocalEvent.googleCalendarEventId != null) {
                try {
                    googleCalendarService.updateEvent(principalUserId, updatedLocalEvent.googleCalendarEventId!!, updatedLocalEvent)
                } catch (e: IllegalStateException) {
                     application.log.info("User $principalUserId has not authorized Google Calendar (or token issue) for updating event ${updatedLocalEvent.id}: ${e.message}")
                } catch (e: Exception) {
                    application.log.error("Failed to update Google Calendar event ${updatedLocalEvent.googleCalendarEventId} for user $principalUserId: ${e.message}", e)
                    // Potentially mark for re-sync
                }
            }
            call.respond(updatedLocalEvent.toResponseDTO())
        }

        delete("/{eventId}") {
            val principalUserId = call.parameters["userId"]?.toIntOrNull()
            val eventId = call.parameters["eventId"]?.toIntOrNull()
            if (principalUserId == null || eventId == null) {
                call.respond(HttpStatusCode.BadRequest, "User ID and Event ID must be integers.")
                return@delete
            }

            val localEvent = eventService.getEventById(eventId)
            if (localEvent == null || localEvent.creatorId != principalUserId) {
                call.respond(HttpStatusCode.NotFound, "Event not found or access denied.")
                return@delete
            }

            if (localEvent.googleCalendarEventId != null) {
                try {
                    googleCalendarService.deleteEvent(principalUserId, localEvent.googleCalendarEventId!!)
                } catch (e: IllegalStateException) {
                     application.log.info("User $principalUserId has not authorized Google Calendar (or token issue) for deleting event ${localEvent.id}: ${e.message}")
                } catch (e: Exception) {
                    // Log error, maybe it was already deleted on Google's side.
                    application.log.error("Failed to delete Google Calendar event ${localEvent.googleCalendarEventId} for user $principalUserId: ${e.message}", e)
                }
            }

            val deletedLocally = eventService.deleteEvent(eventId)
            if (deletedLocally) {
                call.respond(HttpStatusCode.NoContent)
            } else {
                call.respond(HttpStatusCode.InternalServerError, "Failed to delete event locally.")
            }
        }
    }
}
